-- Skillsy Supabase schema
-- Jalankan di Supabase Dashboard > SQL Editor > New query > paste > Run.
-- RLS diaktifkan: backend memakai service key yang melewati RLS,
-- jadi klien publik tidak bisa baca/menulis apa pun.

create table if not exists waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists scans (
  id bigint generated by default as identity primary key,
  job_title text,
  seniority text,
  readiness_score int,
  min_years_required numeric,
  must_skills jsonb,
  missing_skills jsonb,
  created_at timestamptz not null default now()
);

alter table waitlist enable row level security;
alter table scans enable row level security;

-- CV Tailor v1: log pemakaian harian per install-ID (kuota 10/hari/user)
create table if not exists tailor_log (
  id bigint generated by default as identity primary key,
  client_id text not null,
  created_at timestamptz not null default now()
);

alter table tailor_log enable row level security;
